In [ ]:
{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "56dcf326",
   "metadata": {},
   "source": [
    "# 브로드 캐스팅"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6aa6fabe",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "2d7fcdde",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[ 1.  2.  3.  4.]\n",
      " [ 5.  6.  7.  8.]\n",
      " [ 9. 10. 11. 12.]]\n",
      "[1 2 3 4]\n",
      "[[1]\n",
      " [2]\n",
      " [3]\n",
      " [4]]\n",
      "[[[ 1.  2.  3.  4.]]\n",
      "\n",
      " [[ 5.  6.  7.  8.]]\n",
      "\n",
      " [[ 9. 10. 11. 12.]]]\n"
     ]
    }
   ],
   "source": [
    "a1 = np.linspace(1, 12, 12).reshape((3, 4))\n",
    "a2 = np.arange(1, 5)  # [ 1 2 3 4 ]\n",
    "a3 = a2.reshape((4, 1))\n",
    "a4 = a1.reshape((3, 1, 4))\n",
    "print(a1)\n",
    "print(a2)\n",
    "print(a3)\n",
    "print(a4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "c63f6293",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[ 2.  4.  6.  8.]\n",
      " [ 6.  8. 10. 12.]\n",
      " [10. 12. 14. 16.]]\n",
      "(3, 4)\n",
      "[[2 3 4 5]\n",
      " [3 4 5 6]\n",
      " [4 5 6 7]\n",
      " [5 6 7 8]]\n",
      "(4, 4)\n",
      "[[ 1.  2.  3.  4.]\n",
      " [ 5.  6.  7.  8.]\n",
      " [ 9. 10. 11. 12.]]\n",
      "[[[ 1.  2.  3.  4.]]\n",
      "\n",
      " [[ 5.  6.  7.  8.]]\n",
      "\n",
      " [[ 9. 10. 11. 12.]]]\n",
      "[[[ 2.  4.  6.  8.]\n",
      "  [ 6.  8. 10. 12.]\n",
      "  [10. 12. 14. 16.]]\n",
      "\n",
      " [[ 6.  8. 10. 12.]\n",
      "  [10. 12. 14. 16.]\n",
      "  [14. 16. 18. 20.]]\n",
      "\n",
      " [[10. 12. 14. 16.]\n",
      "  [14. 16. 18. 20.]\n",
      "  [18. 20. 22. 24.]]]\n",
      "(3, 3, 4)\n"
     ]
    }
   ],
   "source": [
    "print(a1 + a2)\n",
    "print((a1 + a2).shape)\n",
    "print(a2 + a3)\n",
    "print((a2 + a3).shape)\n",
    "print(a1)\n",
    "print(a4)\n",
    "print(a1 + a4)\n",
    "print((a1 + a4).shape)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4a8c5880",
   "metadata": {},
   "source": [
    "## 인덱싱"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ea753605",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[  1   4   9  16  25  36  49  64  81 100] [ 9 16 25 36 49 64 81]\n",
      "[  100    81    64 10000    36 10000    13 10000     4     1]\n",
      "\n"
     ]
    }
   ],
   "source": [
    "a1 = np.arange(1, 10 + 1) ** 2\n",
    "a2 = a1[2:9]  # 얕은 복사\n",
    "print(a1, a2)\n",
    "a1[3] = a1[1] + a1[2]  # 원소의 변경\n",
    "a2[:5:2] = 10_000\n",
    "# for i in range(len(a1)):\n",
    "#     print(a1[(i + 1) * -1], end=\", \")\n",
    "print(a1[::-1])\n",
    "print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "92823e2f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[[0 1 2 3]\n",
      "  [1 2 3 4]\n",
      "  [2 3 4 5]\n",
      "  [3 4 5 6]\n",
      "  [4 5 6 7]]\n",
      "\n",
      " [[1 2 3 4]\n",
      "  [2 3 4 5]\n",
      "  [3 4 5 6]\n",
      "  [4 5 6 7]\n",
      "  [5 6 7 8]]]\n",
      "[[[ 0  1  2  3]\n",
      "  [ 1  2  3  4]\n",
      "  [ 2  3  4  5]\n",
      "  [ 3  4  5  6]\n",
      "  [ 4  5  6  7]]\n",
      "\n",
      " [[ 1  2  3  4]\n",
      "  [-1 -1 -1  5]\n",
      "  [ 3  4  5  6]\n",
      "  [-1 -1 -1  7]\n",
      "  [ 5  6  7  8]]]\n",
      "[[1 2 3]\n",
      " [3 4 5]]\n",
      "[[-1 -1 -1]\n",
      " [-1 -1 -1]]\n"
     ]
    }
   ],
   "source": [
    "a1 = np.fromfunction(lambda x, y, z: x + y + z, (2, 5, 4), dtype=np.int64)\n",
    "a2 = a1[:, 1::2, :3]  # 얕은 복사\n",
    "\n",
    "print(a1)\n",
    "\n",
    "a2[1, ...] = -1\n",
    "\n",
    "print(a1)\n",
    "\n",
    "for ar in a2:\n",
    "    print(ar)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e5c889ac",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[[0 1 2 3]\n",
      "  [1 2 3 4]\n",
      "  [2 3 4 5]\n",
      "  [3 4 5 6]\n",
      "  [4 5 6 7]]\n",
      "\n",
      " [[1 2 3 4]\n",
      "  [2 3 4 5]\n",
      "  [3 4 5 6]\n",
      "  [4 5 6 7]\n",
      "  [5 6 7 8]]]\n",
      "[[[ 10.  20.  30.  40.]\n",
      "  [ 50.  60.  70.  80.]\n",
      "  [ 90. 100. 110. 120.]\n",
      "  [130. 140. 150. 160.]\n",
      "  [170. 180. 190. 200.]]]\n"
     ]
    }
   ],
   "source": [
    "a1 = np.fromfunction(lambda x, y, z: x + y + z, (2, 5, 4), dtype=np.int64)\n",
    "a2 = np.arange(1, a1.size / 2 + 1).reshape(1, 5, 4) * 10\n",
    "print(a1)\n",
    "print(a2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "1e01983e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[  0.   1.   2.   3.]\n",
      " [  1.   2.   3.   4.]\n",
      " [  2.   3.   4.   5.]\n",
      " [  3.   4.   5.   6.]\n",
      " [  4.   5.   6.   7.]\n",
      " [ 10.  20.  30.  40.]\n",
      " [ 50.  60.  70.  80.]\n",
      " [ 90. 100. 110. 120.]\n",
      " [130. 140. 150. 160.]\n",
      " [170. 180. 190. 200.]]\n",
      "[[  0.   1.   2.   3.  10.  20.  30.  40.]\n",
      " [  1.   2.   3.   4.  50.  60.  70.  80.]\n",
      " [  2.   3.   4.   5.  90. 100. 110. 120.]\n",
      " [  3.   4.   5.   6. 130. 140. 150. 160.]\n",
      " [  4.   5.   6.   7. 170. 180. 190. 200.]]\n",
      "[[[  0.   1.   2.   3.]\n",
      "  [  1.   2.   3.   4.]\n",
      "  [  2.   3.   4.   5.]\n",
      "  [  3.   4.   5.   6.]\n",
      "  [  4.   5.   6.   7.]]\n",
      "\n",
      " [[  1.   2.   3.   4.]\n",
      "  [  2.   3.   4.   5.]\n",
      "  [  3.   4.   5.   6.]\n",
      "  [  4.   5.   6.   7.]\n",
      "  [  5.   6.   7.   8.]]\n",
      "\n",
      " [[ 10.  20.  30.  40.]\n",
      "  [ 50.  60.  70.  80.]\n",
      "  [ 90. 100. 110. 120.]\n",
      "  [130. 140. 150. 160.]\n",
      "  [170. 180. 190. 200.]]]\n",
      "[[  0.   1.   2.   3.]\n",
      " [  1.   2.   3.   4.]\n",
      " [  2.   3.   4.   5.]\n",
      " [  3.   4.   5.   6.]\n",
      " [  4.   5.   6.   7.]\n",
      " [ 10.  20.  30.  40.]\n",
      " [ 50.  60.  70.  80.]\n",
      " [ 90. 100. 110. 120.]\n",
      " [130. 140. 150. 160.]\n",
      " [170. 180. 190. 200.]]\n",
      "[[  0.   1.   2.   3.  10.  20.  30.  40.]\n",
      " [  1.   2.   3.   4.  50.  60.  70.  80.]\n",
      " [  2.   3.   4.   5.  90. 100. 110. 120.]\n",
      " [  3.   4.   5.   6. 130. 140. 150. 160.]\n",
      " [  4.   5.   6.   7. 170. 180. 190. 200.]]\n"
     ]
    }
   ],
   "source": [
    "a3 = np.vstack((a1[0, ...], a2[0, ...]))\n",
    "print(a3)\n",
    "a4 = np.hstack((a1[0, ...], a2[0, ...]))\n",
    "print(a4)\n",
    "a5 = np.concatenate((a1, a2), 0)\n",
    "print(a5)\n",
    "a6 = np.concatenate((a1[0, ...], a2[0, ...]), 0)  # hstack\n",
    "a7 = np.concatenate((a1[0, ...], a2[0, ...]), 1)  # vstack\n",
    "print(a6)\n",
    "print(a7)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "9e9eaf80",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[[ 0  1  2  3]\n",
      "  [ 4  5  6  7]]\n",
      "\n",
      " [[ 8  9 10 11]\n",
      "  [12 13 14 15]]\n",
      "\n",
      " [[16 17 18 19]\n",
      "  [20 21 22 23]]]\n",
      "[[100 100 100 100]\n",
      " [100 100 100 100]]\n",
      "\n",
      "\n",
      "[[ 8  9 10 11]\n",
      " [12 13 14 15]]\n",
      "\n",
      "\n",
      "[[16 17 18 19]\n",
      " [20 21 22 23]]\n",
      "\n",
      "\n",
      "[[100 100 100 100]\n",
      " [  8   9  10  11]\n",
      " [ 16  17  18  19]]\n",
      "\n",
      "\n",
      "[[100 100 100 100]\n",
      " [ 12  13  14  15]\n",
      " [ 20  21  22  23]]\n",
      "[[[100 100 100 100]\n",
      "  [100 100 100 100]]\n",
      "\n",
      " [[  8   9  10  11]\n",
      "  [ 12  13  14  15]]\n",
      "\n",
      " [[ 16  17  18  19]\n",
      "  [ 20  21  22  23]]]\n"
     ]
    }
   ],
   "source": [
    "# split\n",
    "a = np.arange(24).reshape(3, 2, 4)\n",
    "# b1, b2, b3 = np.vsplit(a, 3)  # 얕은 복사\n",
    "# b4, b5 = np.hsplit(a, 2)  # 얕은 복사\n",
    "b1 = a[0, ...]\n",
    "b2 = a[1, ...]\n",
    "b3 = a[2, ...]\n",
    "b4 = a[:, 0, :]\n",
    "b5 = a[:, 1, :]\n",
    "\n",
    "print(a)\n",
    "b1[...] = 100\n",
    "print(b1, b2, b3, b4, b5, sep=\"\\n\\n\\n\")\n",
    "print(a)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3c25db4a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1 2 3 4]\n",
      "\n",
      "\n",
      "[[100   2   3]\n",
      " [100   5   6]]\n",
      "\n",
      "\n",
      "[[[ 10.  20.]\n",
      "  [ 30.  40.]]\n",
      "\n",
      " [[ 50.  60.]\n",
      "  [ 70.  80.]]\n",
      "\n",
      " [[ 90. 100.]\n",
      "  [110. 120.]]]\n",
      "\n",
      "\n",
      "[1 2 3 4]\n",
      "\n",
      "\n",
      "[[100 100]\n",
      " [  2   5]\n",
      " [  3   6]]\n",
      "\n",
      "\n",
      "[[[ 10.  50.  90.]\n",
      "  [ 30.  70. 110.]]\n",
      "\n",
      " [[ 20.  60. 100.]\n",
      "  [ 40.  80. 120.]]]\n"
     ]
    }
   ],
   "source": [
    "a1 = np.arange(1, 5)\n",
    "a2 = np.arange(1, 7).reshape((2, 3))\n",
    "a3 = np.linspace(10, 120, 12).reshape((3, 2, 2))\n",
    "b1 = a1.T\n",
    "b2 = a2.transpose()\n",
    "b2[0] = 100\n",
    "b3 = np.transpose(a3)\n",
    "\n",
    "print(a1, a2, a3, b1, b2, b3, sep=\"\\n\\n\\n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "33744a73",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[ 2 -1  5]\n",
      " [-5  2  2]\n",
      " [ 2  1  3]]\n",
      "\n",
      "\n",
      "[[0 1 0]\n",
      " [1 0 1]\n",
      " [1 1 0]]\n",
      "\n",
      "\n",
      "[ 1 -1  1]\n",
      "\n",
      "\n",
      "[[1]\n",
      " [0]\n",
      " [1]]\n",
      "\n",
      "\n",
      "[[ 4  7 -1]\n",
      " [ 4 -3  2]\n",
      " [ 4  5  1]]\n",
      "\n",
      "\n",
      "[ 8 -5  4]\n",
      "\n",
      "\n",
      "[[ 7]\n",
      " [-3]\n",
      " [ 5]]\n"
     ]
    }
   ],
   "source": [
    "a1 = np.array([[2, -1, 5], [-5, 2, 2], [2, 1, 3]])\n",
    "a2 = np.array([[0, 1, 0], [1, 0, 1], [1, 1, 0]])\n",
    "a3 = np.array([1, -1, 1])\n",
    "a4 = np.array([1, 0, 1]).reshape((3, 1))\n",
    "\n",
    "b1 = np.dot(a1, a2)\n",
    "b2 = a1.dot(a3)\n",
    "b3 = a1.dot(a4)\n",
    "\n",
    "print(a1, a2, a3, a4, b1, b2, b3, sep=\"\\n\\n\\n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "b4bdbc38",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[7 3 7]\n",
      " [7 5 6]\n",
      " [8 0 7]]\n",
      "\n",
      "\n",
      "[[-0.92105263  0.55263158  0.44736842]\n",
      " [ 0.02631579  0.18421053 -0.18421053]\n",
      " [ 1.05263158 -0.63157895 -0.36842105]]\n",
      "\n",
      "\n",
      "[[2 3]\n",
      " [5 6]]\n",
      "\n",
      "\n",
      "[4 7]\n",
      "\n",
      "\n",
      "[-1.  2.]\n"
     ]
    }
   ],
   "source": [
    "a1 = np.random.randint(10, size=(3, 3))\n",
    "a2 = np.linalg.inv(a1)\n",
    "\n",
    "\n",
    "a3 = np.array([[2, 3], [5, 6]])\n",
    "a4 = np.array([4, 7])\n",
    "# a5 = np.linalg.solve(a3, a4)\n",
    "a5 = np.linalg.inv(a3).dot(a4)\n",
    "print(a1, a2, a3, a4, a5, sep=\"\\n\\n\\n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "id": "c5beb0fb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ 0.00000000e+00  1.74524064e-02  3.48994967e-02  5.23359562e-02\n",
      "  6.97564737e-02  8.71557427e-02  1.04528463e-01  1.21869343e-01\n",
      "  1.39173101e-01  1.56434465e-01  1.73648178e-01  1.90808995e-01\n",
      "  2.07911691e-01  2.24951054e-01  2.41921896e-01  2.58819045e-01\n",
      "  2.75637356e-01  2.92371705e-01  3.09016994e-01  3.25568154e-01\n",
      "  3.42020143e-01  3.58367950e-01  3.74606593e-01  3.90731128e-01\n",
      "  4.06736643e-01  4.22618262e-01  4.38371147e-01  4.53990500e-01\n",
      "  4.69471563e-01  4.84809620e-01  5.00000000e-01  5.15038075e-01\n",
      "  5.29919264e-01  5.44639035e-01  5.59192903e-01  5.73576436e-01\n",
      "  5.87785252e-01  6.01815023e-01  6.15661475e-01  6.29320391e-01\n",
      "  6.42787610e-01  6.56059029e-01  6.69130606e-01  6.81998360e-01\n",
      "  6.94658370e-01  7.07106781e-01  7.19339800e-01  7.31353702e-01\n",
      "  7.43144825e-01  7.54709580e-01  7.66044443e-01  7.77145961e-01\n",
      "  7.88010754e-01  7.98635510e-01  8.09016994e-01  8.19152044e-01\n",
      "  8.29037573e-01  8.38670568e-01  8.48048096e-01  8.57167301e-01\n",
      "  8.66025404e-01  8.74619707e-01  8.82947593e-01  8.91006524e-01\n",
      "  8.98794046e-01  9.06307787e-01  9.13545458e-01  9.20504853e-01\n",
      "  9.27183855e-01  9.33580426e-01  9.39692621e-01  9.45518576e-01\n",
      "  9.51056516e-01  9.56304756e-01  9.61261696e-01  9.65925826e-01\n",
      "  9.70295726e-01  9.74370065e-01  9.78147601e-01  9.81627183e-01\n",
      "  9.84807753e-01  9.87688341e-01  9.90268069e-01  9.92546152e-01\n",
      "  9.94521895e-01  9.96194698e-01  9.97564050e-01  9.98629535e-01\n",
      "  9.99390827e-01  9.99847695e-01  1.00000000e+00  9.99847695e-01\n",
      "  9.99390827e-01  9.98629535e-01  9.97564050e-01  9.96194698e-01\n",
      "  9.94521895e-01  9.92546152e-01  9.90268069e-01  9.87688341e-01\n",
      "  9.84807753e-01  9.81627183e-01  9.78147601e-01  9.74370065e-01\n",
      "  9.70295726e-01  9.65925826e-01  9.61261696e-01  9.56304756e-01\n",
      "  9.51056516e-01  9.45518576e-01  9.39692621e-01  9.33580426e-01\n",
      "  9.27183855e-01  9.20504853e-01  9.13545458e-01  9.06307787e-01\n",
      "  8.98794046e-01  8.91006524e-01  8.82947593e-01  8.74619707e-01\n",
      "  8.66025404e-01  8.57167301e-01  8.48048096e-01  8.38670568e-01\n",
      "  8.29037573e-01  8.19152044e-01  8.09016994e-01  7.98635510e-01\n",
      "  7.88010754e-01  7.77145961e-01  7.66044443e-01  7.54709580e-01\n",
      "  7.43144825e-01  7.31353702e-01  7.19339800e-01  7.07106781e-01\n",
      "  6.94658370e-01  6.81998360e-01  6.69130606e-01  6.56059029e-01\n",
      "  6.42787610e-01  6.29320391e-01  6.15661475e-01  6.01815023e-01\n",
      "  5.87785252e-01  5.73576436e-01  5.59192903e-01  5.44639035e-01\n",
      "  5.29919264e-01  5.15038075e-01  5.00000000e-01  4.84809620e-01\n",
      "  4.69471563e-01  4.53990500e-01  4.38371147e-01  4.22618262e-01\n",
      "  4.06736643e-01  3.90731128e-01  3.74606593e-01  3.58367950e-01\n",
      "  3.42020143e-01  3.25568154e-01  3.09016994e-01  2.92371705e-01\n",
      "  2.75637356e-01  2.58819045e-01  2.41921896e-01  2.24951054e-01\n",
      "  2.07911691e-01  1.90808995e-01  1.73648178e-01  1.56434465e-01\n",
      "  1.39173101e-01  1.21869343e-01  1.04528463e-01  8.71557427e-02\n",
      "  6.97564737e-02  5.23359562e-02  3.48994967e-02  1.74524064e-02\n",
      "  1.22464680e-16 -1.74524064e-02 -3.48994967e-02 -5.23359562e-02\n",
      " -6.97564737e-02 -8.71557427e-02 -1.04528463e-01 -1.21869343e-01\n",
      " -1.39173101e-01 -1.56434465e-01 -1.73648178e-01 -1.90808995e-01\n",
      " -2.07911691e-01 -2.24951054e-01 -2.41921896e-01 -2.58819045e-01\n",
      " -2.75637356e-01 -2.92371705e-01 -3.09016994e-01 -3.25568154e-01\n",
      " -3.42020143e-01 -3.58367950e-01 -3.74606593e-01 -3.90731128e-01\n",
      " -4.06736643e-01 -4.22618262e-01 -4.38371147e-01 -4.53990500e-01\n",
      " -4.69471563e-01 -4.84809620e-01 -5.00000000e-01 -5.15038075e-01\n",
      " -5.29919264e-01 -5.44639035e-01 -5.59192903e-01 -5.73576436e-01\n",
      " -5.87785252e-01 -6.01815023e-01 -6.15661475e-01 -6.29320391e-01\n",
      " -6.42787610e-01 -6.56059029e-01 -6.69130606e-01 -6.81998360e-01\n",
      " -6.94658370e-01 -7.07106781e-01 -7.19339800e-01 -7.31353702e-01\n",
      " -7.43144825e-01 -7.54709580e-01 -7.66044443e-01 -7.77145961e-01\n",
      " -7.88010754e-01 -7.98635510e-01 -8.09016994e-01 -8.19152044e-01\n",
      " -8.29037573e-01 -8.38670568e-01 -8.48048096e-01 -8.57167301e-01\n",
      " -8.66025404e-01 -8.74619707e-01 -8.82947593e-01 -8.91006524e-01\n",
      " -8.98794046e-01 -9.06307787e-01 -9.13545458e-01 -9.20504853e-01\n",
      " -9.27183855e-01 -9.33580426e-01 -9.39692621e-01 -9.45518576e-01\n",
      " -9.51056516e-01 -9.56304756e-01 -9.61261696e-01 -9.65925826e-01\n",
      " -9.70295726e-01 -9.74370065e-01 -9.78147601e-01 -9.81627183e-01\n",
      " -9.84807753e-01 -9.87688341e-01 -9.90268069e-01 -9.92546152e-01\n",
      " -9.94521895e-01 -9.96194698e-01 -9.97564050e-01 -9.98629535e-01\n",
      " -9.99390827e-01 -9.99847695e-01 -1.00000000e+00 -9.99847695e-01\n",
      " -9.99390827e-01 -9.98629535e-01 -9.97564050e-01 -9.96194698e-01\n",
      " -9.94521895e-01 -9.92546152e-01 -9.90268069e-01 -9.87688341e-01\n",
      " -9.84807753e-01 -9.81627183e-01 -9.78147601e-01 -9.74370065e-01\n",
      " -9.70295726e-01 -9.65925826e-01 -9.61261696e-01 -9.56304756e-01\n",
      " -9.51056516e-01 -9.45518576e-01 -9.39692621e-01 -9.33580426e-01\n",
      " -9.27183855e-01 -9.20504853e-01 -9.13545458e-01 -9.06307787e-01\n",
      " -8.98794046e-01 -8.91006524e-01 -8.82947593e-01 -8.74619707e-01\n",
      " -8.66025404e-01 -8.57167301e-01 -8.48048096e-01 -8.38670568e-01\n",
      " -8.29037573e-01 -8.19152044e-01 -8.09016994e-01 -7.98635510e-01\n",
      " -7.88010754e-01 -7.77145961e-01 -7.66044443e-01 -7.54709580e-01\n",
      " -7.43144825e-01 -7.31353702e-01 -7.19339800e-01 -7.07106781e-01\n",
      " -6.94658370e-01 -6.81998360e-01 -6.69130606e-01 -6.56059029e-01\n",
      " -6.42787610e-01 -6.29320391e-01 -6.15661475e-01 -6.01815023e-01\n",
      " -5.87785252e-01 -5.73576436e-01 -5.59192903e-01 -5.44639035e-01\n",
      " -5.29919264e-01 -5.15038075e-01 -5.00000000e-01 -4.84809620e-01\n",
      " -4.69471563e-01 -4.53990500e-01 -4.38371147e-01 -4.22618262e-01\n",
      " -4.06736643e-01 -3.90731128e-01 -3.74606593e-01 -3.58367950e-01\n",
      " -3.42020143e-01 -3.25568154e-01 -3.09016994e-01 -2.92371705e-01\n",
      " -2.75637356e-01 -2.58819045e-01 -2.41921896e-01 -2.24951054e-01\n",
      " -2.07911691e-01 -1.90808995e-01 -1.73648178e-01 -1.56434465e-01\n",
      " -1.39173101e-01 -1.21869343e-01 -1.04528463e-01 -8.71557427e-02\n",
      " -6.97564737e-02 -5.23359562e-02 -3.48994967e-02 -1.74524064e-02\n",
      " -2.44929360e-16]\n"
     ]
    }
   ],
   "source": [
    "a1 = np.arange(360 + 1)\n",
    "# a2 = np.sin(a1* np.pi/180 )\n",
    "a2 = np.sin(np.radians(a1))\n",
    "print(a2)\n",
    "\n",
    "np.savez_compressed(\"sin_sample\", x=a1, y=a2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4067b3bf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17\n",
      "  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35\n",
      "  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53\n",
      "  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71\n",
      "  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89\n",
      "  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107\n",
      " 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125\n",
      " 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143\n",
      " 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161\n",
      " 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179\n",
      " 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197\n",
      " 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215\n",
      " 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233\n",
      " 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251\n",
      " 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269\n",
      " 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287\n",
      " 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305\n",
      " 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323\n",
      " 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341\n",
      " 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359\n",
      " 360]\n",
      "[ 0.00000000e+00  1.74524064e-02  3.48994967e-02  5.23359562e-02\n",
      "  6.97564737e-02  8.71557427e-02  1.04528463e-01  1.21869343e-01\n",
      "  1.39173101e-01  1.56434465e-01  1.73648178e-01  1.90808995e-01\n",
      "  2.07911691e-01  2.24951054e-01  2.41921896e-01  2.58819045e-01\n",
      "  2.75637356e-01  2.92371705e-01  3.09016994e-01  3.25568154e-01\n",
      "  3.42020143e-01  3.58367950e-01  3.74606593e-01  3.90731128e-01\n",
      "  4.06736643e-01  4.22618262e-01  4.38371147e-01  4.53990500e-01\n",
      "  4.69471563e-01  4.84809620e-01  5.00000000e-01  5.15038075e-01\n",
      "  5.29919264e-01  5.44639035e-01  5.59192903e-01  5.73576436e-01\n",
      "  5.87785252e-01  6.01815023e-01  6.15661475e-01  6.29320391e-01\n",
      "  6.42787610e-01  6.56059029e-01  6.69130606e-01  6.81998360e-01\n",
      "  6.94658370e-01  7.07106781e-01  7.19339800e-01  7.31353702e-01\n",
      "  7.43144825e-01  7.54709580e-01  7.66044443e-01  7.77145961e-01\n",
      "  7.88010754e-01  7.98635510e-01  8.09016994e-01  8.19152044e-01\n",
      "  8.29037573e-01  8.38670568e-01  8.48048096e-01  8.57167301e-01\n",
      "  8.66025404e-01  8.74619707e-01  8.82947593e-01  8.91006524e-01\n",
      "  8.98794046e-01  9.06307787e-01  9.13545458e-01  9.20504853e-01\n",
      "  9.27183855e-01  9.33580426e-01  9.39692621e-01  9.45518576e-01\n",
      "  9.51056516e-01  9.56304756e-01  9.61261696e-01  9.65925826e-01\n",
      "  9.70295726e-01  9.74370065e-01  9.78147601e-01  9.81627183e-01\n",
      "  9.84807753e-01  9.87688341e-01  9.90268069e-01  9.92546152e-01\n",
      "  9.94521895e-01  9.96194698e-01  9.97564050e-01  9.98629535e-01\n",
      "  9.99390827e-01  9.99847695e-01  1.00000000e+00  9.99847695e-01\n",
      "  9.99390827e-01  9.98629535e-01  9.97564050e-01  9.96194698e-01\n",
      "  9.94521895e-01  9.92546152e-01  9.90268069e-01  9.87688341e-01\n",
      "  9.84807753e-01  9.81627183e-01  9.78147601e-01  9.74370065e-01\n",
      "  9.70295726e-01  9.65925826e-01  9.61261696e-01  9.56304756e-01\n",
      "  9.51056516e-01  9.45518576e-01  9.39692621e-01  9.33580426e-01\n",
      "  9.27183855e-01  9.20504853e-01  9.13545458e-01  9.06307787e-01\n",
      "  8.98794046e-01  8.91006524e-01  8.82947593e-01  8.74619707e-01\n",
      "  8.66025404e-01  8.57167301e-01  8.48048096e-01  8.38670568e-01\n",
      "  8.29037573e-01  8.19152044e-01  8.09016994e-01  7.98635510e-01\n",
      "  7.88010754e-01  7.77145961e-01  7.66044443e-01  7.54709580e-01\n",
      "  7.43144825e-01  7.31353702e-01  7.19339800e-01  7.07106781e-01\n",
      "  6.94658370e-01  6.81998360e-01  6.69130606e-01  6.56059029e-01\n",
      "  6.42787610e-01  6.29320391e-01  6.15661475e-01  6.01815023e-01\n",
      "  5.87785252e-01  5.73576436e-01  5.59192903e-01  5.44639035e-01\n",
      "  5.29919264e-01  5.15038075e-01  5.00000000e-01  4.84809620e-01\n",
      "  4.69471563e-01  4.53990500e-01  4.38371147e-01  4.22618262e-01\n",
      "  4.06736643e-01  3.90731128e-01  3.74606593e-01  3.58367950e-01\n",
      "  3.42020143e-01  3.25568154e-01  3.09016994e-01  2.92371705e-01\n",
      "  2.75637356e-01  2.58819045e-01  2.41921896e-01  2.24951054e-01\n",
      "  2.07911691e-01  1.90808995e-01  1.73648178e-01  1.56434465e-01\n",
      "  1.39173101e-01  1.21869343e-01  1.04528463e-01  8.71557427e-02\n",
      "  6.97564737e-02  5.23359562e-02  3.48994967e-02  1.74524064e-02\n",
      "  1.22464680e-16 -1.74524064e-02 -3.48994967e-02 -5.23359562e-02\n",
      " -6.97564737e-02 -8.71557427e-02 -1.04528463e-01 -1.21869343e-01\n",
      " -1.39173101e-01 -1.56434465e-01 -1.73648178e-01 -1.90808995e-01\n",
      " -2.07911691e-01 -2.24951054e-01 -2.41921896e-01 -2.58819045e-01\n",
      " -2.75637356e-01 -2.92371705e-01 -3.09016994e-01 -3.25568154e-01\n",
      " -3.42020143e-01 -3.58367950e-01 -3.74606593e-01 -3.90731128e-01\n",
      " -4.06736643e-01 -4.22618262e-01 -4.38371147e-01 -4.53990500e-01\n",
      " -4.69471563e-01 -4.84809620e-01 -5.00000000e-01 -5.15038075e-01\n",
      " -5.29919264e-01 -5.44639035e-01 -5.59192903e-01 -5.73576436e-01\n",
      " -5.87785252e-01 -6.01815023e-01 -6.15661475e-01 -6.29320391e-01\n",
      " -6.42787610e-01 -6.56059029e-01 -6.69130606e-01 -6.81998360e-01\n",
      " -6.94658370e-01 -7.07106781e-01 -7.19339800e-01 -7.31353702e-01\n",
      " -7.43144825e-01 -7.54709580e-01 -7.66044443e-01 -7.77145961e-01\n",
      " -7.88010754e-01 -7.98635510e-01 -8.09016994e-01 -8.19152044e-01\n",
      " -8.29037573e-01 -8.38670568e-01 -8.48048096e-01 -8.57167301e-01\n",
      " -8.66025404e-01 -8.74619707e-01 -8.82947593e-01 -8.91006524e-01\n",
      " -8.98794046e-01 -9.06307787e-01 -9.13545458e-01 -9.20504853e-01\n",
      " -9.27183855e-01 -9.33580426e-01 -9.39692621e-01 -9.45518576e-01\n",
      " -9.51056516e-01 -9.56304756e-01 -9.61261696e-01 -9.65925826e-01\n",
      " -9.70295726e-01 -9.74370065e-01 -9.78147601e-01 -9.81627183e-01\n",
      " -9.84807753e-01 -9.87688341e-01 -9.90268069e-01 -9.92546152e-01\n",
      " -9.94521895e-01 -9.96194698e-01 -9.97564050e-01 -9.98629535e-01\n",
      " -9.99390827e-01 -9.99847695e-01 -1.00000000e+00 -9.99847695e-01\n",
      " -9.99390827e-01 -9.98629535e-01 -9.97564050e-01 -9.96194698e-01\n",
      " -9.94521895e-01 -9.92546152e-01 -9.90268069e-01 -9.87688341e-01\n",
      " -9.84807753e-01 -9.81627183e-01 -9.78147601e-01 -9.74370065e-01\n",
      " -9.70295726e-01 -9.65925826e-01 -9.61261696e-01 -9.56304756e-01\n",
      " -9.51056516e-01 -9.45518576e-01 -9.39692621e-01 -9.33580426e-01\n",
      " -9.27183855e-01 -9.20504853e-01 -9.13545458e-01 -9.06307787e-01\n",
      " -8.98794046e-01 -8.91006524e-01 -8.82947593e-01 -8.74619707e-01\n",
      " -8.66025404e-01 -8.57167301e-01 -8.48048096e-01 -8.38670568e-01\n",
      " -8.29037573e-01 -8.19152044e-01 -8.09016994e-01 -7.98635510e-01\n",
      " -7.88010754e-01 -7.77145961e-01 -7.66044443e-01 -7.54709580e-01\n",
      " -7.43144825e-01 -7.31353702e-01 -7.19339800e-01 -7.07106781e-01\n",
      " -6.94658370e-01 -6.81998360e-01 -6.69130606e-01 -6.56059029e-01\n",
      " -6.42787610e-01 -6.29320391e-01 -6.15661475e-01 -6.01815023e-01\n",
      " -5.87785252e-01 -5.73576436e-01 -5.59192903e-01 -5.44639035e-01\n",
      " -5.29919264e-01 -5.15038075e-01 -5.00000000e-01 -4.84809620e-01\n",
      " -4.69471563e-01 -4.53990500e-01 -4.38371147e-01 -4.22618262e-01\n",
      " -4.06736643e-01 -3.90731128e-01 -3.74606593e-01 -3.58367950e-01\n",
      " -3.42020143e-01 -3.25568154e-01 -3.09016994e-01 -2.92371705e-01\n",
      " -2.75637356e-01 -2.58819045e-01 -2.41921896e-01 -2.24951054e-01\n",
      " -2.07911691e-01 -1.90808995e-01 -1.73648178e-01 -1.56434465e-01\n",
      " -1.39173101e-01 -1.21869343e-01 -1.04528463e-01 -8.71557427e-02\n",
      " -6.97564737e-02 -5.23359562e-02 -3.48994967e-02 -1.74524064e-02\n",
      " -2.44929360e-16]\n"
     ]
    }
   ],
   "source": [
    "a3 = np.load(\"sin_sample.npz\")\n",
    "print(a3[\"x\"])\n",
    "print(a3[\"y\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "id": "21bdb024",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(2, 3, 4, 3)\n",
      "[[[[9. 9. 9.]\n",
      "   [9. 9. 9.]\n",
      "   [9. 9. 9.]\n",
      "   [9. 9. 9.]]\n",
      "\n",
      "  [[9. 9. 9.]\n",
      "   [9. 9. 9.]\n",
      "   [9. 9. 9.]\n",
      "   [9. 9. 9.]]\n",
      "\n",
      "  [[9. 9. 9.]\n",
      "   [9. 9. 9.]\n",
      "   [9. 9. 9.]\n",
      "   [9. 9. 9.]]]\n",
      "\n",
      "\n",
      " [[[9. 9. 9.]\n",
      "   [9. 9. 9.]\n",
      "   [9. 9. 9.]\n",
      "   [9. 9. 9.]]\n",
      "\n",
      "  [[9. 9. 9.]\n",
      "   [9. 9. 9.]\n",
      "   [9. 9. 9.]\n",
      "   [9. 9. 9.]]\n",
      "\n",
      "  [[9. 9. 9.]\n",
      "   [9. 9. 9.]\n",
      "   [9. 9. 9.]\n",
      "   [9. 9. 9.]]]]\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "\n",
    "# A = np.ones((2, 3, 4, 1, 3, 9))\n",
    "# B = np.ones((7, 4, 9, 3))  # 9가 맞춰져야함 (A의 마지막, B의 두 번째)\n",
    "# C = np.dot(A, B)\n",
    "# print(C.shape)  # (2, 3, 4, 1, 3, 7, 4, 3)\n",
    "# print(C)\n",
    "\n",
    "A = np.ones((2, 3, 9))\n",
    "B = np.ones((4, 9, 3))  # 9가 맞춰져야함 (A의 마지막, B의 두 번째)\n",
    "C = np.dot(A, B)\n",
    "print(C.shape)  # (2, 3, 4, 1, 3, 7, 4, 3)\n",
    "print(C)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1dd337a1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}